### **Assignment: Introduction to Linear Algebra and NumPy**

#### **Objective:**
This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.


### **Working with NumPy**

NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

**Task 1:** 
- Import the `numpy` library and check its version.


In [15]:
# Solution Here
import numpy as np
np.__version__


'2.4.0'


### **Creating a NumPy Array:**

NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

**Task 2:**
- Create a 1D NumPy array from a Python list of numbers: `[1, 2, 3, 4, 5]`.
- Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
- Generate an array of 10 evenly spaced values between 0 and 5.

In [39]:
# Solution Here
import numpy as np
list_number = np.array([1,2,3,4,5])
list_number


array([1, 2, 3, 4, 5])

In [40]:
arr = np.arange(1,10) .reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr = np.linspace(0,5,10)
arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### **Indexing and Slicing Arrays:**

Indexing and slicing allow you to access and modify specific elements of an array.

**Task 3:**
- Access the element in the second row, third column of the 2D array you created above.
- Slice the first two rows and the first two columns from the same array.
- Modify the value in the last row and first column to 100.


In [46]:
# Solution Here
arr = np.arange(1,10) .reshape(3,3)
element= arr[1,2]
element


np.int64(6)

In [50]:
rc_arr = arr[:2,:2]
rc_arr

array([[1, 2],
       [4, 5]])

In [51]:
arr[-1,0]=100
arr

array([[  1,   2,   3],
       [  4,   5,   6],
       [100,   8,   9]])

### **Properties and Methods of NumPy Arrays**

NumPy arrays have several useful properties and methods.

**Task 4:**
- Find the shape, size, and data type of the 2D array.
- Change the 1D array into a 2D array of shape (5,1).
- Flatten a multi-dimensional array back into a 1D array.

In [67]:
# Solution Here
arr.shape



(3, 3)

In [68]:
arr.size

9

In [69]:
arr.dtype

dtype('int64')

In [73]:
list_number = np.array([1,2,3,4,5])
list_number=list_number.reshape(5,1)
list_number

array([[1],
       [2],
       [3],
       [4],
       [5]])

### **Operations on NumPy Arrays**

Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

**Task 5:**
- Add 5 to every element in the 1D array.
- Multiply the 2D array by 3.
- Perform matrix multiplication between the following two arrays:  
    ```python
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

In [74]:
# Solution Here
list_number = np.array([1,2,3,4,5])
add_element = list_number+5
add_element


array([ 6,  7,  8,  9, 10])

In [78]:
arr = np.arange(1,10) .reshape(3,3)
mul= arr * 3
mul


array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [80]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
mul_arr = np.dot(A,B)
mul_arr

array([[19, 22],
       [43, 50]])

In [82]:
#or
mul_arr = A@B
mul_arr

array([[19, 22],
       [43, 50]])

### **Understanding Broadcasting**

Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

**Task 6:**
- Create a 3x3 matrix of ones and a 1D array of length 3.
- Add the 1D array to each row of the matrix using broadcasting.

In [84]:
# Solution Here
A = np.ones((3,3))
b= np.array([1,2,3])
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [89]:
b

array([1, 2, 3])

In [90]:
broadcasting = A + b
broadcasting

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])