In [1]:
!pip install numpy


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 10.6 MB/s  0:00:000.6 MB/s eta 0:00:01


In [2]:
!pip install skilearn

  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 11.6 MB/s  0:00:00.7 MB/s eta 0:00:01:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 11.4 MB/s  0:00:00
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 11.8 MB/s  0:00:01 11.9 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/13 [skilearn]m━━━━━━ 11/13 [fastapi]]


In [3]:
!pip install pandas

In [8]:
!pip install sql


  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for sql: filename=sql-2022.4.0-py3-none-any.whl size=4378 sha256=fcaf1550de336ee51c79888cc7d819a10dcb68a5731d0977bfa66c91ff6592bc
  Stored in directory: /Users/ganeshpokharel/Library/Caches/pip/wheels/b9/f5/43/10aae492653e6ae01b8fa471562fb9f1b2e4f91ad01f573c88
Successfully built sql


In [14]:
!pip install numpy pandas matplotlib seaborn scipy statsmodels scikit-learn xgboost lightgbm catboost tensorflow keras torch torchvision nltk spacy gensim openpyxl xlrd beautifulsoup4 requests plotly bokeh dash


In [1]:
import numpy as np


In [2]:
np.__version__

'2.4.0'

# Creating Numpy array

In [3]:
list1 = [2,3,4]

In [6]:
arr1 = np.array(list1)

In [7]:
arr1

array([2, 3, 4])

In [8]:
arr1.shape

(3,)

In [9]:
arr1.ndim

1

In [10]:
list1 = [[[2,3,4],[6,7,8], [6,8,0]],[[2,3,4],[6,7,8], [6,8,0]]]

In [11]:
arr1 = np.array(list1)

In [12]:
arr1

array([[[2, 3, 4],
        [6, 7, 8],
        [6, 8, 0]],

       [[2, 3, 4],
        [6, 7, 8],
        [6, 8, 0]]])

In [13]:
arr1.shape

(2, 3, 3)

In [14]:
arr1.ndim

3

In [ ]:
NumPy arrays can be created in several ways. Here are some of the most common methods:

1.array(): Creates NumPy arrays from Python lists
2.zeros(): Creates NumPy arrays with all elements initialized to 0
3.ones(): Creates NumPy arrays with all elements initialized to 1
4.full(): Creates an array with all elements initialized to same user-specified value
5.arange(): Creates NumPy arrays with a sequence of values (similar to python range() function)
6.linspace(): Creates NumPy arrays with a sequence of evenly spaced values
7.diag(): Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
8.eye(): Creates NumPy array with ones on the diagonal and zeros elsewhere
9.identity(): Creates an identity matrix
10.random.rand(): Creates NumPy array of random numbers sampled from a uniform distribution


In [16]:
np.zeros((2,3,4),dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [21]:
np.full((2,3,4),fill_value =6)

array([[[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]],

       [[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]]])

In [23]:
np.arange(2,90,5)

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82,
       87])

In [24]:
arr2 = np.linspace( (0,1,2) ,(10,20,30), num = 5)
arr2

array([[ 0.  ,  1.  ,  2.  ],
       [ 2.5 ,  5.75,  9.  ],
       [ 5.  , 10.5 , 16.  ],
       [ 7.5 , 15.25, 23.  ],
       [10.  , 20.  , 30.  ]])

In [25]:
arr2.shape

(5, 3)

In [26]:
arr2.ndim


2

In [27]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [28]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.randint(0,10,size = (2,3))

array([[1, 8, 9],
       [6, 2, 5]])

In [30]:
np.random.randint(0,50,size = (4,2,3))

array([[[10, 44, 40],
        [19, 27,  2]],

       [[28, 35, 14],
        [12, 12, 37]],

       [[33, 15, 45],
        [ 5, 25, 42]],

       [[36, 44, 44],
        [23, 35, 40]]])

# Accessing an Array


### Indexing and Slicing NumPy Arrays

NumPy arrays can be indexed and sliced in several ways depending on the number of dimensions.

### Indexing:
Indexing follows a simple rule that we may have encountered before. Let's give it a try.

1D Array: array_name[idx] (Similar to Python list)

2D Array: array_name[row_idx, col_idx] (Similar to Matrix)

ND Array: array_name[dim1_idx, dim2_idx, ..., dimN_idx]


OR

2D Array: array_name[row_idx][col_idx]

ND Array: array_name[dim1_idx][dim2_idx] ... [dimN_idx]

### Slicing:

Slicing follows the same rule as indexing. The only difference is that for each dimension we provide it with a range of indeces and sometimes (optional) step size (similar to arange() function discussed above).

1. 1D Array: array_name[idx1:idx2:step]

2. 2D Array: array_name[row_idx1:row_idx2:step1, col_idx1:col_idx2:step2]
3. ND Array: array_name[dim1_idx1:dim1_idx2:step1, ..., dimN_idx1:dimN_idx2:stepN]

In [9]:
import numpy as np
a = np.array([1,2,3,4,5,6]) #1Dim


In [10]:
print(a[-3])

4


In [11]:
a[2::1]

array([3, 4, 5, 6])

In [12]:
#2D
arr = np.random.randint(0,10,size=(5,4))
arr

array([[0, 1, 4, 6],
       [3, 1, 5, 1],
       [7, 0, 0, 7],
       [5, 4, 5, 1],
       [7, 5, 5, 6]])

In [13]:
arr[1,0] #arr[1] [0]

np.int64(3)

In [14]:
arr[-1,-1]

np.int64(6)

In [15]:
# Slicing 2D array : (array[<row_slice>, <col_slice>])
arr[1:3, 0:3]

array([[3, 1, 5],
       [7, 0, 0]])

In [16]:
arr[:2,3]

array([6, 1])

In [17]:
# 3D
arr = np.random.randint(0,10,size = (3,4,3))
arr

array([[[1, 0, 3],
        [4, 7, 5],
        [4, 5, 3],
        [1, 2, 7]],

       [[3, 2, 8],
        [3, 1, 0],
        [9, 4, 4],
        [0, 6, 8]],

       [[5, 2, 5],
        [2, 0, 9],
        [6, 7, 4],
        [2, 4, 8]]])

In [18]:
arr[1, -1, 2]

np.int64(8)

In [19]:
arr[1]

array([[3, 2, 8],
       [3, 1, 0],
       [9, 4, 4],
       [0, 6, 8]])

In [20]:
arr[:, :2, :]

array([[[1, 0, 3],
        [4, 7, 5]],

       [[3, 2, 8],
        [3, 1, 0]],

       [[5, 2, 5],
        [2, 0, 9]]])

In [21]:
dataset = np.random.randint(0,255, (16,3,720,720))


In [22]:
dataset.shape

(16, 3, 720, 720)

In [23]:
dataset[0,1, :,:]

array([[248, 249, 186, ..., 141, 158,  74],
       [ 74,  82, 123, ...,  71, 125,  50],
       [ 62,  95, 110, ..., 209,   0,  55],
       ...,
       [154, 166, 220, ..., 149,  15, 135],
       [193,  77, 225, ..., 152,  34, 159],
       [167, 129, 150, ..., 119, 181,  62]], shape=(720, 720))