# NumPy Array Properties and Methods

1. shape: Property that returns the dimensions of the array

2. ndim: Property that returns number of array dimensions

3. dtype: Property that returns data-type of the array’s elements

4. T: Transpose of the array’s elements

5. reshape(): Method to change the dimensions of an array. The product of old dimensions should match the product of new dimensions

6. ravel(): Method that collapses all values into a single axis or dimension and returns view of original array

7. flatten(): Method that collapses all values into a single axis or dimension and returns an independent copy of original array

8. sum(): Method that returns the sum of all elements in an array

9. cumsum(): Method that returns cumulative sum over given axis

10. prod(): Method that compute product over given axis

11. max(): Method that returns the maximum along a given axis

12. argmax(): Method that returns indeces of the maximum values along a given axis

13. clip(): Clip values beyond range to threshold values

14. np.concatenate(): Method to concatenate two or more arrays

15. np.split(): Method to split an array into multiple sub-arrays

16. np.vstack(): Method to stack arrays vertically

17. np.hstack(): Method to stack arrays horizontally

In [4]:
import numpy as np

In [8]:
a = np.random.randint(10,50 ,(5,4,3))


In [7]:
a.shape

(5, 4, 3)

In [9]:
a.ndim

3

In [10]:
a.dtype

dtype('int64')

In [11]:
a.size # Number of elements


60

In [12]:
a.T # Matrix Transpose ( rows to columns , and columns to row)

array([[[10, 41, 20, 31, 10],
        [36, 28, 32, 28, 28],
        [18, 38, 33, 32, 16],
        [11, 27, 25, 45, 46]],

       [[17, 22, 42, 31, 32],
        [21, 38, 29, 13, 43],
        [12, 10, 20, 30, 34],
        [26, 38, 47, 14, 32]],

       [[47, 15, 28, 45, 34],
        [45, 15, 33, 11, 19],
        [38, 38, 39, 12, 24],
        [37, 44, 19, 26, 20]]])

In [13]:
a = np.random.randint(10, 50, size = (5,4))
a

array([[19, 25, 28, 33],
       [35, 29, 44, 41],
       [17, 21, 33, 45],
       [22, 14, 34, 44],
       [39, 13, 33, 11]])

In [14]:
a.reshape(10,2)

array([[19, 25],
       [28, 33],
       [35, 29],
       [44, 41],
       [17, 21],
       [33, 45],
       [22, 14],
       [34, 44],
       [39, 13],
       [33, 11]])

In [15]:
a.reshape(-1,5)

array([[19, 25, 28, 33, 35],
       [29, 44, 41, 17, 21],
       [33, 45, 22, 14, 34],
       [44, 39, 13, 33, 11]])

In [16]:
b = a.flatten() # a.ravel()
b

array([19, 25, 28, 33, 35, 29, 44, 41, 17, 21, 33, 45, 22, 14, 34, 44, 39,
       13, 33, 11])

In [17]:
a

array([[19, 25, 28, 33],
       [35, 29, 44, 41],
       [17, 21, 33, 45],
       [22, 14, 34, 44],
       [39, 13, 33, 11]])

In [18]:
a.sum(axis = 0)

array([132, 102, 172, 174])

In [19]:
a.sum(axis = 1)

array([105, 149, 116, 114,  96])

### 0 -> column wise -> vertival    \\\\\\\  1 -> row wise -> horizontal

In [21]:
np.trace(a)

np.int64(125)

In [22]:
np.cumsum(a, axis = 0)

array([[ 19,  25,  28,  33],
       [ 54,  54,  72,  74],
       [ 71,  75, 105, 119],
       [ 93,  89, 139, 163],
       [132, 102, 172, 174]])

In [23]:
np.prod(a, axis = 1)

array([ 438900, 1831060,  530145,  460768,  184041])

In [24]:
np.max(a, axis = 1)

array([33, 44, 45, 44, 39])

In [25]:
a

array([[19, 25, 28, 33],
       [35, 29, 44, 41],
       [17, 21, 33, 45],
       [22, 14, 34, 44],
       [39, 13, 33, 11]])

In [26]:
np.max(a, axis = 0)

array([39, 29, 44, 45])

In [27]:
np.argmax(a, axis =0) 

array([4, 1, 1, 2])

In [28]:
np.clip(a, 20, 30)

array([[20, 25, 28, 30],
       [30, 29, 30, 30],
       [20, 21, 30, 30],
       [22, 20, 30, 30],
       [30, 20, 30, 20]])

In [29]:
arr1 = np.random.randint(1,100, size = (3,3))
arr2 = np.random.randint(1,100, size = (3,3))

In [30]:
arr1

array([[42,  4, 39],
       [93, 15, 34],
       [80, 78, 64]])

In [31]:
arr2

array([[66,  7, 44],
       [62, 97, 80],
       [91, 42, 71]])

In [32]:
d = np.concatenate([arr1,arr2], axis=0)
d

array([[42,  4, 39],
       [93, 15, 34],
       [80, 78, 64],
       [66,  7, 44],
       [62, 97, 80],
       [91, 42, 71]])

In [33]:
d = np.concatenate([arr1,arr2], axis=1)
d

array([[42,  4, 39, 66,  7, 44],
       [93, 15, 34, 62, 97, 80],
       [80, 78, 64, 91, 42, 71]])

In [34]:
np.vstack([arr1,arr2])

array([[42,  4, 39],
       [93, 15, 34],
       [80, 78, 64],
       [66,  7, 44],
       [62, 97, 80],
       [91, 42, 71]])

In [35]:
np.hstack((arr1,arr2))

array([[42,  4, 39, 66,  7, 44],
       [93, 15, 34, 62, 97, 80],
       [80, 78, 64, 91, 42, 71]])

In [36]:
np.split(d, 3, axis=1)

[array([[42,  4],
        [93, 15],
        [80, 78]]),
 array([[39, 66],
        [34, 62],
        [64, 91]]),
 array([[ 7, 44],
        [97, 80],
        [42, 71]])]