## 1. Elementwise Operations

In [7]:
import numpy as np

In [2]:
a = np.array(
    [
        [4,5,6],
        [1,2,4]
    ]
)
b = np.array([[8,6,0],[3,2,4]])
c = np.array([[8,4,0],[3,11,4]])

In [3]:
a,b

(array([[4, 5, 6],
        [1, 2, 4]]),
 array([[8, 6, 0],
        [3, 2, 4]]))

In [4]:
a,c

(array([[4, 5, 6],
        [1, 2, 4]]),
 array([[ 8,  4,  0],
        [ 3, 11,  4]]))

In [5]:
b,c

(array([[8, 6, 0],
        [3, 2, 4]]),
 array([[ 8,  4,  0],
        [ 3, 11,  4]]))

# Arithmetic Operations

In [9]:
np.add(a,b)

array([[12, 11,  6],
       [ 4,  4,  8]])

In [11]:
np.subtract(a,b)

array([[-4, -1,  6],
       [-2,  0,  0]])

In [13]:
np.pow(a,2) #a ** 2

array([[16, 25, 36],
       [ 1,  4, 16]])

In [14]:
# a % b
quo , rem = np.divmod(a,b)
quo

/var/folders/bt/pcxs82x914b3zh57lplprzg80000gn/T/ipykernel_74533/1124160517.py:2: RuntimeWarning: divide by zero encountered in divmod
  quo , rem = np.divmod(a,b)


array([[0, 0, 0],
       [0, 1, 1]])

In [15]:
rem

array([[4, 5, 0],
       [1, 0, 0]])

# Trignometric

In [17]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.84147098,  0.90929743, -0.7568025 ]])

In [18]:
np.cos(b)

array([[-0.14550003,  0.96017029,  1.        ],
       [-0.9899925 , -0.41614684, -0.65364362]])

In [19]:
np.tan(c)

array([[-6.79971146e+00,  1.15782128e+00,  0.00000000e+00],
       [-1.42546543e-01, -2.25950846e+02,  1.15782128e+00]])

In [20]:
cot = 1 / np.tan(a)
cot

array([[ 0.86369115, -0.29581292, -3.436353  ],
       [ 0.64209262, -0.45765755,  0.86369115]])

# Rounding operations

In [21]:
np.around(cot,2)

array([[ 0.86, -0.3 , -3.44],
       [ 0.64, -0.46,  0.86]])

In [22]:
np.floor(cot)

array([[ 0., -1., -4.],
       [ 0., -1.,  0.]])

In [23]:
np.ceil(cot)

array([[ 1., -0., -3.],
       [ 1., -0.,  1.]])

## 2. Matrix Operations

In [24]:
b = np.random.randint(0,10, (3,4))

In [25]:
a,b

(array([[4, 5, 6],
        [1, 2, 4]]),
 array([[3, 1, 0, 7],
        [2, 5, 0, 6],
        [6, 7, 6, 6]]))

In [26]:
# a @ b
res = np.dot(a,b)

In [27]:
res

array([[58, 71, 36, 94],
       [31, 39, 24, 43]])

In [28]:
# a.T
np.transpose(a)

array([[4, 1],
       [5, 2],
       [6, 4]])

In [29]:
np.trace(b) # Diagonal sum

np.int64(14)

In [33]:
# Inverse of an matrix

sq = np.random.randint(0,10, (3,3))
a_det = np.linalg.det(sq)

In [34]:
a_det

np.float64(44.000000000000014)

In [35]:
inv_sq = np.linalg.inv(sq)

In [36]:
np.dot(sq, inv_sq).round()

array([[ 1.,  0.,  0.],
       [-0.,  1., -0.],
       [-0.,  0.,  1.]])

### Solve Equation : 4x + 2y = 8 , 5x + 3y = 9

In [37]:
a = np.array(
    [
        [4,2],
        [5,3]
    ]
)
b = np.array([8,9])

In [38]:
a_inv = np.linalg.inv(a)

In [39]:
a_inv

array([[ 1.5, -1. ],
       [-2.5,  2. ]])

In [40]:
np.dot(a_inv,b)

array([ 3., -2.])

In [41]:
# x = 3, y = -2

In [42]:
## Array Broadcasting

In [43]:
a * b

array([[32, 18],
       [40, 27]])