In [13]:
import numpy as np

In [2]:
np.__version__

'2.4.0'

In [3]:
list1 = [1,2,3,4,5,6,7,8]
arr = np.array(list1)

In [4]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr.shape

(8,)

In [6]:
arr.ndim

1

In [8]:
list2 = [[1,2,3],[4,5,6],[7,8,9],[0,3,4]]
arr1 = np.array(list2)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 3, 4]])

In [9]:
arr1.shape

(4, 3)

In [10]:
arr1.ndim

2

In [31]:
np.zeros((3,2,4),dtype=bool)

array([[[False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False, False, False, False]]])

In [30]:
np.ones((1,2,3), dtype = bool)

array([[[ True,  True,  True],
        [ True,  True,  True]]])

In [25]:
np.full((2,3,4), fill_value = 3)

array([[[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]])

In [33]:
np.arange(3,100,5)

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83,
       88, 93, 98])

In [38]:
np.linspace((1,9,2),(10,20,30), num = 5)

array([[ 1.  ,  9.  ,  2.  ],
       [ 3.25, 11.75,  9.  ],
       [ 5.5 , 14.5 , 16.  ],
       [ 7.75, 17.25, 23.  ],
       [10.  , 20.  , 30.  ]])

In [44]:
np.diag([2,8,4])

array([[2, 0, 0],
       [0, 8, 0],
       [0, 0, 4]])

In [53]:
np.eye(1,2,3)

array([[0., 0.]])

In [57]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
import numpy as np
np.random.randint(0,50,size = (4,3,2))

array([[[20,  0],
        [ 6, 47],
        [27, 46]],

       [[ 2, 31],
        [ 4, 19],
        [47, 47]],

       [[37, 37],
        [33, 25],
        [26, 14]],

       [[17,  7],
        [33, 49],
        [21, 15]]])

In [17]:
np.ndim

<function ndim at 0x10cfa26b0>

In [18]:
np.shape

<function shape at 0x10cfa0530>

In [19]:
np.size

<function size at 0x10cfa2870>